/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.login;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author chris
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public String nombreUsuario;
    private boolean clickbutton;
    
    public Inicio() {
        initComponents();
        SetImageLabel(Icono, "src/com/images/logo2.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_principal = new javax.swing.JPanel();
        Barra = new javax.swing.JPanel();
        Icono = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();
        Lb_Bienvenida = new javax.swing.JLabel();
        Pn_botones = new javax.swing.JPanel();
        Bt_ventas = new javax.swing.JPanel();
        lb_ventas = new javax.swing.JLabel();
        Bt_inventario = new javax.swing.JPanel();
        lb_inventario = new javax.swing.JLabel();
        Bt_gst_usuarios = new javax.swing.JPanel();
        lb_gst_usuarios = new javax.swing.JLabel();
        Bt_gst_clientes = new javax.swing.JPanel();
        lb_gst_clientes = new javax.swing.JLabel();
        Bt_departamentos = new javax.swing.JPanel();
        lb_departamentos = new javax.swing.JLabel();
        Bt_trabajadores = new javax.swing.JPanel();
        lb_trabajadores = new javax.swing.JLabel();
        Bt_facturas = new javax.swing.JPanel();
        lb_facturas = new javax.swing.JLabel();
        Bt_productos = new javax.swing.JPanel();
        lb_productos = new javax.swing.JLabel();

        bg_principal.setBackground(new java.awt.Color(255, 255, 255));
        bg_principal.setLayout(null);

        Barra.setBackground(new java.awt.Color(255, 220, 3));
        Barra.setLayout(null);
        Barra.add(Icono);
        Icono.setBounds(30, 0, 150, 50);

        bg_principal.add(Barra);
        Barra.setBounds(0, 0, 1024, 50);

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setLayout(null);

        Lb_Bienvenida.setFont(new java.awt.Font("Poppins Light", 0, 36)); // NOI18N
        Lb_Bienvenida.setForeground(new java.awt.Color(0, 0, 0));
        Lb_Bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_Bienvenida.setText("Bienvenido");
        Container.add(Lb_Bienvenida);
        Lb_Bienvenida.setBounds(60, 80, 730, 55);

        bg_principal.add(Container);
        Container.setBounds(200, 50, 824, 550);

        Pn_botones.setBackground(new java.awt.Color(204, 204, 204));
        Pn_botones.setLayout(null);

        Bt_ventas.setBackground(new java.awt.Color(204, 204, 204));
        Bt_ventas.setForeground(new java.awt.Color(0, 0, 0));
        Bt_ventas.setLayout(new java.awt.CardLayout());

        lb_ventas.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        lb_ventas.setForeground(new java.awt.Color(0, 0, 0));
        lb_ventas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ventas.setText("Ventas");
        lb_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ventasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_ventasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_ventasMouseExited(evt);
            }
        });
        Bt_ventas.add(lb_ventas, "card2");

        Pn_botones.add(Bt_ventas);
        Bt_ventas.setBounds(0, 0, 200, 68);

        Bt_inventario.setBackground(new java.awt.Color(204, 204, 204));
        Bt_inventario.setLayout(new java.awt.CardLayout());

        lb_inventario.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        lb_inventario.setForeground(new java.awt.Color(0, 0, 0));
        lb_inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_inventario.setText("Inventario");
        lb_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_inventarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_inventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_inventarioMouseExited(evt);
            }
        });
        Bt_inventario.add(lb_inventario, "card2");

        Pn_botones.add(Bt_inventario);
        Bt_inventario.setBounds(0, 69, 200, 68);

        Bt_gst_usuarios.setBackground(new java.awt.Color(204, 204, 204));
        Bt_gst_usuarios.setLayout(new java.awt.CardLayout());

        lb_gst_usuarios.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        lb_gst_usuarios.setForeground(new java.awt.Color(0, 0, 0));
        lb_gst_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_gst_usuarios.setText("Gestión de Usuarios");
        lb_gst_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_gst_usuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_gst_usuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_gst_usuariosMouseExited(evt);
            }
        });
        Bt_gst_usuarios.add(lb_gst_usuarios, "card2");

        Pn_botones.add(Bt_gst_usuarios);
        Bt_gst_usuarios.setBounds(0, 138, 200, 68);

        Bt_gst_clientes.setBackground(new java.awt.Color(204, 204, 204));
        Bt_gst_clientes.setLayout(new java.awt.CardLayout());

        lb_gst_clientes.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        lb_gst_clientes.setForeground(new java.awt.Color(0, 0, 0));
        lb_gst_clientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_gst_clientes.setText("Gestión de Clientes");
        lb_gst_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_gst_clientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_gst_clientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_gst_clientesMouseExited(evt);
            }
        });
        Bt_gst_clientes.add(lb_gst_clientes, "card2");

        Pn_botones.add(Bt_gst_clientes);
        Bt_gst_clientes.setBounds(0, 207, 200, 68);

        Bt_departamentos.setBackground(new java.awt.Color(204, 204, 204));
        Bt_departamentos.setLayout(new java.awt.CardLayout());

        lb_departamentos.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        lb_departamentos.setForeground(new java.awt.Color(0, 0, 0));
        lb_departamentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_departamentos.setText("Departamentos");
        lb_departamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_departamentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_departamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_departamentosMouseExited(evt);
            }
        });
        Bt_departamentos.add(lb_departamentos, "card2");

        Pn_botones.add(Bt_departamentos);
        Bt_departamentos.setBounds(0, 276, 200, 68);

        Bt_trabajadores.setBackground(new java.awt.Color(204, 204, 204));
        Bt_trabajadores.setLayout(new java.awt.CardLayout());

        lb_trabajadores.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        lb_trabajadores.setForeground(new java.awt.Color(0, 0, 0));
        lb_trabajadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_trabajadores.setText("Trabajadores");
        lb_trabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_trabajadoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_trabajadoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_trabajadoresMouseExited(evt);
            }
        });
        Bt_trabajadores.add(lb_trabajadores, "card2");

        Pn_botones.add(Bt_trabajadores);
        Bt_trabajadores.setBounds(0, 345, 200, 68);

        Bt_facturas.setBackground(new java.awt.Color(204, 204, 204));
        Bt_facturas.setLayout(new java.awt.CardLayout());

        lb_facturas.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        lb_facturas.setForeground(new java.awt.Color(0, 0, 0));
        lb_facturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_facturas.setText("Facturas");
        lb_facturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_facturasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_facturasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_facturasMouseExited(evt);
            }
        });
        Bt_facturas.add(lb_facturas, "card2");

        Pn_botones.add(Bt_facturas);
        Bt_facturas.setBounds(0, 414, 200, 68);

        Bt_productos.setBackground(new java.awt.Color(204, 204, 204));
        Bt_productos.setLayout(new java.awt.CardLayout());

        lb_productos.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        lb_productos.setForeground(new java.awt.Color(0, 0, 0));
        lb_productos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_productos.setText("Añadir Productos");
        lb_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_productosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_productosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_productosMouseExited(evt);
            }
        });
        Bt_productos.add(lb_productos, "card2");

        Pn_botones.add(Bt_productos);
        Bt_productos.setBounds(0, 483, 200, 68);

        bg_principal.add(Pn_botones);
        Pn_botones.setBounds(0, 50, 200, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lb_ventasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ventasMouseEntered
        Bt_ventas.setBackground(new Color(153 , 153, 153));
    }//GEN-LAST:event_lb_ventasMouseEntered

    private void lb_ventasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ventasMouseExited
        Bt_ventas.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_lb_ventasMouseExited

    private void lb_inventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_inventarioMouseEntered
        Bt_inventario.setBackground(new Color(153 , 153, 153));
    }//GEN-LAST:event_lb_inventarioMouseEntered

    private void lb_inventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_inventarioMouseExited
        Bt_inventario.setBackground(new Color(204 , 204, 204));
    }//GEN-LAST:event_lb_inventarioMouseExited

    private void lb_gst_usuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_gst_usuariosMouseEntered
        Bt_gst_usuarios.setBackground(new Color(153 , 153, 153));
    }//GEN-LAST:event_lb_gst_usuariosMouseEntered

    private void lb_gst_usuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_gst_usuariosMouseExited
        Bt_gst_usuarios.setBackground(new Color(204 , 204, 204));
    }//GEN-LAST:event_lb_gst_usuariosMouseExited

    private void lb_gst_clientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_gst_clientesMouseEntered
        Bt_gst_clientes.setBackground(new Color(153 , 153, 153));
    }//GEN-LAST:event_lb_gst_clientesMouseEntered

    private void lb_gst_clientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_gst_clientesMouseExited
        Bt_gst_clientes.setBackground(new Color(204 , 204, 204));
    }//GEN-LAST:event_lb_gst_clientesMouseExited

    private void lb_departamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_departamentosMouseEntered
        Bt_departamentos.setBackground(new Color(153 , 153, 153));
    }//GEN-LAST:event_lb_departamentosMouseEntered

    private void lb_departamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_departamentosMouseExited
        Bt_departamentos.setBackground(new Color(204 , 204, 204));
    }//GEN-LAST:event_lb_departamentosMouseExited

    private void lb_trabajadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_trabajadoresMouseEntered
        Bt_trabajadores.setBackground(new Color(153 , 153, 153));
    }//GEN-LAST:event_lb_trabajadoresMouseEntered

    private void lb_trabajadoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_trabajadoresMouseExited
        Bt_trabajadores.setBackground(new Color(204 , 204, 204));
    }//GEN-LAST:event_lb_trabajadoresMouseExited

    private void lb_facturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_facturasMouseEntered
        Bt_facturas.setBackground(new Color(153 , 153, 153));
    }//GEN-LAST:event_lb_facturasMouseEntered

    private void lb_facturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_facturasMouseExited
        Bt_facturas.setBackground(new Color(204 , 204, 204));
    }//GEN-LAST:event_lb_facturasMouseExited

    private void lb_productosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_productosMouseEntered
        Bt_productos.setBackground(new Color(153 , 153, 153));
    }//GEN-LAST:event_lb_productosMouseEntered

    private void lb_productosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_productosMouseExited
        Bt_productos.setBackground(new Color(204 , 204, 204));
    }//GEN-LAST:event_lb_productosMouseExited

    private void lb_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ventasMouseClicked
        Bt_ventas.setBackground(new Color(102 , 102, 102));
        
        Ventas ventas = new Ventas();
        ventas.setSize(824, 550);
        ventas.setLocation(0, 0);
        
        Container.removeAll();
        Container.add(ventas, BorderLayout.CENTER);
        Container.revalidate();
        Container.repaint();
        
    }//GEN-LAST:event_lb_ventasMouseClicked

    private void lb_inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_inventarioMouseClicked
        Bt_inventario.setBackground(new Color(102 , 102, 102));
    }//GEN-LAST:event_lb_inventarioMouseClicked

    private void lb_gst_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_gst_usuariosMouseClicked
        Bt_gst_usuarios.setBackground(new Color(102 , 102, 102));
    }//GEN-LAST:event_lb_gst_usuariosMouseClicked

    private void lb_gst_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_gst_clientesMouseClicked
        Bt_gst_clientes.setBackground(new Color(102 , 102, 102));
    }//GEN-LAST:event_lb_gst_clientesMouseClicked

    private void lb_departamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_departamentosMouseClicked
        Bt_departamentos.setBackground(new Color(102 , 102, 102));
    }//GEN-LAST:event_lb_departamentosMouseClicked

    private void lb_trabajadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_trabajadoresMouseClicked
        Bt_trabajadores.setBackground(new Color(102 , 102, 102));
    }//GEN-LAST:event_lb_trabajadoresMouseClicked

    private void lb_facturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_facturasMouseClicked
        Bt_facturas.setBackground(new Color(102 , 102, 102));
    }//GEN-LAST:event_lb_facturasMouseClicked

    private void lb_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_productosMouseClicked
        Bt_productos.setBackground(new Color(102 , 102, 102));
    }//GEN-LAST:event_lb_productosMouseClicked

    private void SetImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    public void SetBienvenidaLabel(){
        Lb_Bienvenida.setText("Bienvenido " + this.nombreUsuario);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JPanel Bt_departamentos;
    private javax.swing.JPanel Bt_facturas;
    private javax.swing.JPanel Bt_gst_clientes;
    private javax.swing.JPanel Bt_gst_usuarios;
    private javax.swing.JPanel Bt_inventario;
    private javax.swing.JPanel Bt_productos;
    private javax.swing.JPanel Bt_trabajadores;
    private javax.swing.JPanel Bt_ventas;
    private javax.swing.JPanel Container;
    private javax.swing.JLabel Icono;
    private javax.swing.JLabel Lb_Bienvenida;
    private javax.swing.JPanel Pn_botones;
    private javax.swing.JPanel bg_principal;
    private javax.swing.JLabel lb_departamentos;
    private javax.swing.JLabel lb_facturas;
    private javax.swing.JLabel lb_gst_clientes;
    private javax.swing.JLabel lb_gst_usuarios;
    private javax.swing.JLabel lb_inventario;
    private javax.swing.JLabel lb_productos;
    private javax.swing.JLabel lb_trabajadores;
    private javax.swing.JLabel lb_ventas;
    // End of variables declaration//GEN-END:variables
}
