/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.login;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author chris
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
       
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Panel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Lb_Contrasenia = new javax.swing.JLabel();
        Fld_Contrasenia = new javax.swing.JPasswordField();
        Sep_Contrasenia = new javax.swing.JSeparator();
        Lb_usuario = new javax.swing.JLabel();
        Fld_usuario = new javax.swing.JTextField();
        Sep_Usuario = new javax.swing.JSeparator();
        Bt_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(null);

        Panel.setBackground(new java.awt.Color(255, 220, 3));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.png"))); // NOI18N
        Logo.setText("jLabel2");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 512, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        bg.add(Panel);
        Panel.setBounds(0, 0, 512, 600);

        Lb_Contrasenia.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        Lb_Contrasenia.setForeground(new java.awt.Color(0, 51, 153));
        Lb_Contrasenia.setText("Contraseña");
        bg.add(Lb_Contrasenia);
        Lb_Contrasenia.setBounds(580, 300, 360, 60);

        Fld_Contrasenia.setBackground(new java.awt.Color(255, 255, 255));
        Fld_Contrasenia.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        Fld_Contrasenia.setForeground(new java.awt.Color(153, 153, 153));
        Fld_Contrasenia.setText("**********");
        Fld_Contrasenia.setToolTipText("Ingresar Contraseña");
        Fld_Contrasenia.setBorder(null);
        Fld_Contrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Fld_ContraseniaMousePressed(evt);
            }
        });
        bg.add(Fld_Contrasenia);
        Fld_Contrasenia.setBounds(580, 350, 350, 40);
        bg.add(Sep_Contrasenia);
        Sep_Contrasenia.setBounds(580, 390, 350, 2);

        Lb_usuario.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        Lb_usuario.setForeground(new java.awt.Color(0, 51, 153));
        Lb_usuario.setText("Usuario");
        bg.add(Lb_usuario);
        Lb_usuario.setBounds(580, 100, 360, 60);

        Fld_usuario.setBackground(new java.awt.Color(255, 255, 255));
        Fld_usuario.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        Fld_usuario.setForeground(new java.awt.Color(153, 153, 153));
        Fld_usuario.setText("Ingresar Usuario");
        Fld_usuario.setBorder(null);
        Fld_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Fld_usuarioMousePressed(evt);
            }
        });
        Fld_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fld_usuarioActionPerformed(evt);
            }
        });
        bg.add(Fld_usuario);
        Fld_usuario.setBounds(580, 150, 350, 40);
        bg.add(Sep_Usuario);
        Sep_Usuario.setBounds(580, 190, 350, 10);

        Bt_login.setBackground(new java.awt.Color(0, 51, 153));
        Bt_login.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        Bt_login.setForeground(new java.awt.Color(255, 255, 255));
        Bt_login.setText("Login");
        Bt_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt_loginMouseExited(evt);
            }
        });
        Bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_loginActionPerformed(evt);
            }
        });
        bg.add(Bt_login);
        Bt_login.setBounds(680, 470, 170, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_loginActionPerformed
        try{
        if (Fld_usuario.getText().equals("Ingresar Usuario") || Fld_usuario.getText().equals("") || String.valueOf(Fld_Contrasenia.getPassword()).equals("**********") || String.valueOf(Fld_Contrasenia.getPassword()).equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor Ingrese usuario y contraseña");                
        } else {
            //JOptionPane.showMessageDialog(null, "Bienvenido " + Fld_usuario.getText());    
            Inicio inicio = new Inicio();
            inicio.setSize(1024, 600);
            inicio.setLocation(0, 0);
            inicio.nombreUsuario = Fld_usuario.getText();
            inicio.SetBienvenidaLabel();
            
            bg.removeAll();
            bg.add(inicio, BorderLayout.CENTER);
            bg.revalidate();
            bg.repaint();
        }            
        } catch (HeadlessException e){
            JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
        }

    }//GEN-LAST:event_Bt_loginActionPerformed
     
    private void Fld_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fld_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fld_usuarioActionPerformed

    private void Bt_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_loginMouseEntered
        Bt_login.setBackground(new Color(55 , 120, 248));
    }//GEN-LAST:event_Bt_loginMouseEntered

    private void Bt_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_loginMouseExited
        Bt_login.setBackground(new Color(0 , 51, 153));
    }//GEN-LAST:event_Bt_loginMouseExited

    private void Fld_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fld_usuarioMousePressed
        if (Fld_usuario.getText().equals("Ingresar Usuario")) {
            Fld_usuario.setText("");
            Fld_usuario.setForeground(Color.black);
        }
        
        if (String.valueOf(Fld_Contrasenia.getPassword()).isEmpty()) {
            Fld_Contrasenia.setText("**********");
            Fld_Contrasenia.setForeground(new Color(153, 153, 153));            
        }        
    }//GEN-LAST:event_Fld_usuarioMousePressed

    private void Fld_ContraseniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fld_ContraseniaMousePressed
        if (Fld_Contrasenia.getText().equals("**********")) {
            Fld_Contrasenia.setText("");
            Fld_Contrasenia.setForeground(Color.black);
        }
        
        if (String.valueOf(Fld_usuario.getText()).isEmpty()) {
            Fld_usuario.setText("Ingresar Usuario");
            Fld_usuario.setForeground(new Color(153, 153, 153));
        }  
    }//GEN-LAST:event_Fld_ContraseniaMousePressed

    public String MostrarNombreUsuario (){
        String nombreUsuario = Fld_usuario.getText();
        return nombreUsuario;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_login;
    private javax.swing.JPasswordField Fld_Contrasenia;
    private javax.swing.JTextField Fld_usuario;
    private javax.swing.JLabel Lb_Contrasenia;
    private javax.swing.JLabel Lb_usuario;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Panel;
    private javax.swing.JSeparator Sep_Contrasenia;
    private javax.swing.JSeparator Sep_Usuario;
    private javax.swing.JPanel bg;
    // End of variables declaration//GEN-END:variables
}
